package cs1302.arcade;

import javafx.scene.transform.Rotate;
import javafx.geometry.Point2D;
import cs1302.arcade.Ship;
import javafx.scene.shape.Polygon;
import java.util.Random;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javafx.event.EventHandler;
import javafx.scene.input.KeyEvent;
import javafx.scene.input.KeyCode;
import javafx.scene.input.MouseEvent;
import cs1302.arcade.MainMenu;
import cs1302.arcade.Asteroid;
import cs1302.arcade.Controls;

/**
 * Application subclass for {@code ArcadeApp}.
 * @version 2019.fa
 */

public class ArcadeApp extends Application {
//    Group group = new Group();           // main container
//    Random rng = new Random();           // random number generator
//    Rectangle r = new Rectangle(20, 20); // some rectangle
    ChessBoard chess;// = new ChessBoard();
    AsteroidsGame asteroids;
    Asteroid[] gameAsteroids;
    MainMenu menu = new MainMenu();
    Controls controls;

    /**
     * Return a key event handler that moves to the rectangle to the left
     * or the right depending on what key event is generated by the associated
     * node.
     * @return the key event handler
     */

    private EventHandler<? super KeyEvent> createKeyHandler(Stage stage, Scene scene) {
        return event -> {
            switch (event.getCode()) {
            case Q:
                System.exit(0);
                break;
            case DIGIT1:
                chess = new ChessBoard();
                chess.getSwitch(stage, scene);
                stage.setScene(chess.getScene());
                break;
            case DIGIT2:
                asteroids = new AsteroidsGame();
                gameAsteroids = asteroids.getAsteroids();
                asteroids.getSwitch(stage, scene);
                stage.setScene(asteroids.getScene());
                startAsteroids();
                break;
            case DIGIT3:
                controls = new Controls();
                controls.getSwitch(stage, scene);
                stage.setScene(controls.getScene());
                break;
            } // switch
        };
    } // createKeyHandler

    public void startAsteroids() {
        for (Asteroid a : gameAsteroids) {
            a.getTimeLine().play();
        }
    }

    /** {@inheritDoc} */
    @Override
    public void start(Stage stage) {

        //Scene scene = new Scene(group, 640, 480);
        Scene scene = menu.getScene();
        menu.getRoot().setOnKeyPressed(createKeyHandler(stage, scene));
        menu.getSwitch(stage, scene);
        stage.setTitle("cs1302-arcade!");
        stage.setScene(scene);
        stage.sizeToScene();
        stage.show();

        menu.getRoot().requestFocus();
    } // start

} // ArcadeApp
